// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: advertiser.sql

package sqlcgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const createAdvertiser = `-- name: CreateAdvertiser :one
INSERT INTO advertiser (advertiser_id, name, country, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING advertiser_id, name, country, created_at, updated_at
`

type CreateAdvertiserParams struct {
	AdvertiserID uuid.UUID
	Name         string
	Country      string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateAdvertiser(ctx context.Context, arg CreateAdvertiserParams) (Advertiser, error) {
	row := q.db.QueryRow(ctx, createAdvertiser,
		arg.AdvertiserID,
		arg.Name,
		arg.Country,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Advertiser
	err := row.Scan(
		&i.AdvertiserID,
		&i.Name,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAdvertiser = `-- name: DeleteAdvertiser :exec
DELETE FROM advertiser WHERE advertiser_id = $1
`

func (q *Queries) DeleteAdvertiser(ctx context.Context, advertiserID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAdvertiser, advertiserID)
	return err
}

const getAdvertiserByID = `-- name: GetAdvertiserByID :one
SELECT advertiser_id, name, country, created_at, updated_at
FROM advertiser
WHERE advertiser_id = $1
`

func (q *Queries) GetAdvertiserByID(ctx context.Context, advertiserID uuid.UUID) (Advertiser, error) {
	row := q.db.QueryRow(ctx, getAdvertiserByID, advertiserID)
	var i Advertiser
	err := row.Scan(
		&i.AdvertiserID,
		&i.Name,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdvertiserByIDForUpdate = `-- name: GetAdvertiserByIDForUpdate :one
SELECT advertiser_id, name, country, created_at, updated_at
FROM advertiser
WHERE advertiser_id = $1
FOR UPDATE
`

func (q *Queries) GetAdvertiserByIDForUpdate(ctx context.Context, advertiserID uuid.UUID) (Advertiser, error) {
	row := q.db.QueryRow(ctx, getAdvertiserByIDForUpdate, advertiserID)
	var i Advertiser
	err := row.Scan(
		&i.AdvertiserID,
		&i.Name,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveAdvertiser = `-- name: SaveAdvertiser :one
UPDATE advertiser
SET name = $2, country = $3, updated_at = $4
WHERE advertiser_id = $1
RETURNING advertiser_id, name, country, created_at, updated_at
`

type SaveAdvertiserParams struct {
	AdvertiserID uuid.UUID
	Name         string
	Country      string
	UpdatedAt    time.Time
}

func (q *Queries) SaveAdvertiser(ctx context.Context, arg SaveAdvertiserParams) (Advertiser, error) {
	row := q.db.QueryRow(ctx, saveAdvertiser,
		arg.AdvertiserID,
		arg.Name,
		arg.Country,
		arg.UpdatedAt,
	)
	var i Advertiser
	err := row.Scan(
		&i.AdvertiserID,
		&i.Name,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
