// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: advertiser.sql

package sqlcgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const create = `-- name: Create :one
INSERT INTO advertiser (advertiser_id, name, country, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING advertiser_id, name, country, created_at, updated_at
`

type CreateParams struct {
	AdvertiserID uuid.UUID
	Name         string
	Country      string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Advertiser, error) {
	row := q.db.QueryRow(ctx, create,
		arg.AdvertiserID,
		arg.Name,
		arg.Country,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Advertiser
	err := row.Scan(
		&i.AdvertiserID,
		&i.Name,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM advertiser WHERE advertiser_id = $1
`

func (q *Queries) Delete(ctx context.Context, advertiserID uuid.UUID) error {
	_, err := q.db.Exec(ctx, delete, advertiserID)
	return err
}

const getByID = `-- name: GetByID :one
SELECT advertiser_id, name, country, created_at, updated_at
FROM advertiser
WHERE advertiser_id = $1
`

func (q *Queries) GetByID(ctx context.Context, advertiserID uuid.UUID) (Advertiser, error) {
	row := q.db.QueryRow(ctx, getByID, advertiserID)
	var i Advertiser
	err := row.Scan(
		&i.AdvertiserID,
		&i.Name,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getByIDForUpdate = `-- name: GetByIDForUpdate :one
SELECT advertiser_id, name, country, created_at, updated_at
FROM advertiser
WHERE advertiser_id = $1
FOR UPDATE
`

func (q *Queries) GetByIDForUpdate(ctx context.Context, advertiserID uuid.UUID) (Advertiser, error) {
	row := q.db.QueryRow(ctx, getByIDForUpdate, advertiserID)
	var i Advertiser
	err := row.Scan(
		&i.AdvertiserID,
		&i.Name,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const save = `-- name: Save :one
UPDATE advertiser
SET name = $2, country = $3, updated_at = $4
WHERE advertiser_id = $1
RETURNING advertiser_id, name, country, created_at, updated_at
`

type SaveParams struct {
	AdvertiserID uuid.UUID
	Name         string
	Country      string
	UpdatedAt    time.Time
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) (Advertiser, error) {
	row := q.db.QueryRow(ctx, save,
		arg.AdvertiserID,
		arg.Name,
		arg.Country,
		arg.UpdatedAt,
	)
	var i Advertiser
	err := row.Scan(
		&i.AdvertiserID,
		&i.Name,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
