// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaign.sql

package sqlcgen

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaign (campaign_id, advertiser_id, name, budget_total, budget_daily, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING campaign_id, advertiser_id, name, budget_total, budget_daily,
          spend_total, spend_today, spend_day, status, pause_reason, created_at, updated_at
`

type CreateCampaignParams struct {
	CampaignID   uuid.UUID
	AdvertiserID uuid.UUID
	Name         string
	BudgetTotal  int64
	BudgetDaily  int64
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.CampaignID,
		arg.AdvertiserID,
		arg.Name,
		arg.BudgetTotal,
		arg.BudgetDaily,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Campaign
	err := row.Scan(
		&i.CampaignID,
		&i.AdvertiserID,
		&i.Name,
		&i.BudgetTotal,
		&i.BudgetDaily,
		&i.SpendTotal,
		&i.SpendToday,
		&i.SpendDay,
		&i.Status,
		&i.PauseReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :exec
DELETE FROM campaign WHERE campaign_id = $1
`

func (q *Queries) DeleteCampaign(ctx context.Context, campaignID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCampaign, campaignID)
	return err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT campaign_id, advertiser_id, name, budget_total, budget_daily,
       spend_total, spend_today, spend_day, status, pause_reason, created_at, updated_at
FROM campaign
WHERE campaign_id = $1
`

func (q *Queries) GetCampaignByID(ctx context.Context, campaignID uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByID, campaignID)
	var i Campaign
	err := row.Scan(
		&i.CampaignID,
		&i.AdvertiserID,
		&i.Name,
		&i.BudgetTotal,
		&i.BudgetDaily,
		&i.SpendTotal,
		&i.SpendToday,
		&i.SpendDay,
		&i.Status,
		&i.PauseReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaignByIDForUpdate = `-- name: GetCampaignByIDForUpdate :one
SELECT campaign_id, advertiser_id, name, budget_total, budget_daily,
       spend_total, spend_today, spend_day, status, pause_reason, created_at, updated_at
FROM campaign
WHERE campaign_id = $1
FOR UPDATE
`

func (q *Queries) GetCampaignByIDForUpdate(ctx context.Context, campaignID uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByIDForUpdate, campaignID)
	var i Campaign
	err := row.Scan(
		&i.CampaignID,
		&i.AdvertiserID,
		&i.Name,
		&i.BudgetTotal,
		&i.BudgetDaily,
		&i.SpendTotal,
		&i.SpendToday,
		&i.SpendDay,
		&i.Status,
		&i.PauseReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pauseCampaign = `-- name: PauseCampaign :one
UPDATE campaign
SET status = 'paused', pause_reason = $2, updated_at = $3
WHERE campaign_id = $1 AND status = 'active'
RETURNING campaign_id, advertiser_id, name, budget_total, budget_daily,
          spend_total, spend_today, spend_day, status, pause_reason, created_at, updated_at
`

type PauseCampaignParams struct {
	CampaignID  uuid.UUID
	PauseReason *string
	UpdatedAt   time.Time
}

func (q *Queries) PauseCampaign(ctx context.Context, arg PauseCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, pauseCampaign, arg.CampaignID, arg.PauseReason, arg.UpdatedAt)
	var i Campaign
	err := row.Scan(
		&i.CampaignID,
		&i.AdvertiserID,
		&i.Name,
		&i.BudgetTotal,
		&i.BudgetDaily,
		&i.SpendTotal,
		&i.SpendToday,
		&i.SpendDay,
		&i.Status,
		&i.PauseReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resumeCampaign = `-- name: ResumeCampaign :one
UPDATE campaign
SET status = 'active', pause_reason = NULL, updated_at = $2
WHERE campaign_id = $1 AND status = 'paused'
RETURNING campaign_id, advertiser_id, name, budget_total, budget_daily,
          spend_total, spend_today, spend_day, status, pause_reason, created_at, updated_at
`

type ResumeCampaignParams struct {
	CampaignID uuid.UUID
	UpdatedAt  time.Time
}

func (q *Queries) ResumeCampaign(ctx context.Context, arg ResumeCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, resumeCampaign, arg.CampaignID, arg.UpdatedAt)
	var i Campaign
	err := row.Scan(
		&i.CampaignID,
		&i.AdvertiserID,
		&i.Name,
		&i.BudgetTotal,
		&i.BudgetDaily,
		&i.SpendTotal,
		&i.SpendToday,
		&i.SpendDay,
		&i.Status,
		&i.PauseReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveCampaign = `-- name: SaveCampaign :one
UPDATE campaign
SET name = $2, budget_total = $3, budget_daily = $4, updated_at = $5
WHERE campaign_id = $1
RETURNING campaign_id, advertiser_id, name, budget_total, budget_daily,
          spend_total, spend_today, spend_day, status, pause_reason, created_at, updated_at
`

type SaveCampaignParams struct {
	CampaignID  uuid.UUID
	Name        string
	BudgetTotal int64
	BudgetDaily int64
	UpdatedAt   time.Time
}

func (q *Queries) SaveCampaign(ctx context.Context, arg SaveCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, saveCampaign,
		arg.CampaignID,
		arg.Name,
		arg.BudgetTotal,
		arg.BudgetDaily,
		arg.UpdatedAt,
	)
	var i Campaign
	err := row.Scan(
		&i.CampaignID,
		&i.AdvertiserID,
		&i.Name,
		&i.BudgetTotal,
		&i.BudgetDaily,
		&i.SpendTotal,
		&i.SpendToday,
		&i.SpendDay,
		&i.Status,
		&i.PauseReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
