// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdGroup struct {
	AdGroupID     uuid.UUID
	CampaignID    uuid.UUID
	Name          string
	TargetCountry pgtype.Text
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Advertiser struct {
	AdvertiserID uuid.UUID
	Name         string
	Country      string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Campaign struct {
	CampaignID   uuid.UUID
	AdvertiserID uuid.UUID
	Name         string
	BudgetTotal  int64
	BudgetDaily  int64
	SpendTotal   int64
	SpendToday   int64
	SpendDay     pgtype.Date
	Status       string
	PauseReason  pgtype.Text
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
