// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	sqlcgen "github.com/iPatrushevSergey/adpace/app/internal/campaign/adapter/repository/postgres/sqlcgen"
	entity "github.com/iPatrushevSergey/adpace/app/internal/campaign/domain/entity"
)

type AdvertiserConverterImpl struct{}

func (c *AdvertiserConverterImpl) ToCreateParams(source entity.Advertiser) (sqlcgen.CreateParams, error) {
	var sqlcgenCreateParams sqlcgen.CreateParams
	uuidUUID, err := StringToUUID(source.AdvertiserID)
	if err != nil {
		return sqlcgenCreateParams, err
	}
	sqlcgenCreateParams.AdvertiserID = uuidUUID
	sqlcgenCreateParams.Name = source.Name
	sqlcgenCreateParams.Country = source.Country
	sqlcgenCreateParams.CreatedAt = CopyTime(source.CreatedAt)
	sqlcgenCreateParams.UpdatedAt = CopyTime(source.UpdatedAt)
	return sqlcgenCreateParams, nil
}
func (c *AdvertiserConverterImpl) ToEntityAdvertiser(source sqlcgen.Advertiser) entity.Advertiser {
	var entityAdvertiser entity.Advertiser
	entityAdvertiser.AdvertiserID = UUIDToString(source.AdvertiserID)
	entityAdvertiser.Name = source.Name
	entityAdvertiser.Country = source.Country
	entityAdvertiser.CreatedAt = CopyTime(source.CreatedAt)
	entityAdvertiser.UpdatedAt = CopyTime(source.UpdatedAt)
	return entityAdvertiser
}
func (c *AdvertiserConverterImpl) ToPutParams(source entity.Advertiser) (sqlcgen.PutParams, error) {
	var sqlcgenPutParams sqlcgen.PutParams
	uuidUUID, err := StringToUUID(source.AdvertiserID)
	if err != nil {
		return sqlcgenPutParams, err
	}
	sqlcgenPutParams.AdvertiserID = uuidUUID
	sqlcgenPutParams.Name = source.Name
	sqlcgenPutParams.Country = source.Country
	sqlcgenPutParams.UpdatedAt = CopyTime(source.UpdatedAt)
	return sqlcgenPutParams, nil
}
