// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	sqlcgen "github.com/iPatrushevSergey/adpace/app/internal/campaign/adapter/repository/postgres/sqlcgen"
	entity "github.com/iPatrushevSergey/adpace/app/internal/campaign/domain/entity"
)

type AdvertiserConverterImpl struct{}

func (c *AdvertiserConverterImpl) ToCreateAdvertiserParams(source entity.Advertiser) (sqlcgen.CreateAdvertiserParams, error) {
	var sqlcgenCreateAdvertiserParams sqlcgen.CreateAdvertiserParams
	uuidUUID, err := StringToUUID(source.AdvertiserID)
	if err != nil {
		return sqlcgenCreateAdvertiserParams, err
	}
	sqlcgenCreateAdvertiserParams.AdvertiserID = uuidUUID
	sqlcgenCreateAdvertiserParams.Name = source.Name
	sqlcgenCreateAdvertiserParams.Country = source.Country
	sqlcgenCreateAdvertiserParams.CreatedAt = CopyTime(source.CreatedAt)
	sqlcgenCreateAdvertiserParams.UpdatedAt = CopyTime(source.UpdatedAt)
	return sqlcgenCreateAdvertiserParams, nil
}
func (c *AdvertiserConverterImpl) ToEntityAdvertiser(source sqlcgen.Advertiser) entity.Advertiser {
	var entityAdvertiser entity.Advertiser
	entityAdvertiser.AdvertiserID = UUIDToString(source.AdvertiserID)
	entityAdvertiser.Name = source.Name
	entityAdvertiser.Country = source.Country
	entityAdvertiser.CreatedAt = CopyTime(source.CreatedAt)
	entityAdvertiser.UpdatedAt = CopyTime(source.UpdatedAt)
	return entityAdvertiser
}
func (c *AdvertiserConverterImpl) ToSaveAdvertiserParams(source entity.Advertiser) (sqlcgen.SaveAdvertiserParams, error) {
	var sqlcgenSaveAdvertiserParams sqlcgen.SaveAdvertiserParams
	uuidUUID, err := StringToUUID(source.AdvertiserID)
	if err != nil {
		return sqlcgenSaveAdvertiserParams, err
	}
	sqlcgenSaveAdvertiserParams.AdvertiserID = uuidUUID
	sqlcgenSaveAdvertiserParams.Name = source.Name
	sqlcgenSaveAdvertiserParams.Country = source.Country
	sqlcgenSaveAdvertiserParams.UpdatedAt = CopyTime(source.UpdatedAt)
	return sqlcgenSaveAdvertiserParams, nil
}
