// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	sqlcgen "github.com/iPatrushevSergey/adpace/app/internal/campaign/adapter/repository/postgres/sqlcgen"
	entity "github.com/iPatrushevSergey/adpace/app/internal/campaign/domain/entity"
)

type CampaignConverterImpl struct{}

func (c *CampaignConverterImpl) ToCreateCampaignParams(source entity.Campaign) (sqlcgen.CreateCampaignParams, error) {
	var sqlcgenCreateCampaignParams sqlcgen.CreateCampaignParams
	uuidUUID, err := StringToUUID(source.CampaignID)
	if err != nil {
		return sqlcgenCreateCampaignParams, err
	}
	sqlcgenCreateCampaignParams.CampaignID = uuidUUID
	uuidUUID2, err := StringToUUID(source.AdvertiserID)
	if err != nil {
		return sqlcgenCreateCampaignParams, err
	}
	sqlcgenCreateCampaignParams.AdvertiserID = uuidUUID2
	sqlcgenCreateCampaignParams.Name = source.Name
	sqlcgenCreateCampaignParams.BudgetTotal = source.BudgetTotal
	sqlcgenCreateCampaignParams.BudgetDaily = source.BudgetDaily
	sqlcgenCreateCampaignParams.Status = source.Status
	sqlcgenCreateCampaignParams.CreatedAt = CopyTime(source.CreatedAt)
	sqlcgenCreateCampaignParams.UpdatedAt = CopyTime(source.UpdatedAt)
	return sqlcgenCreateCampaignParams, nil
}
func (c *CampaignConverterImpl) ToEntityCampaign(source sqlcgen.Campaign) entity.Campaign {
	var entityCampaign entity.Campaign
	entityCampaign.CampaignID = UUIDToString(source.CampaignID)
	entityCampaign.AdvertiserID = UUIDToString(source.AdvertiserID)
	entityCampaign.Name = source.Name
	entityCampaign.BudgetTotal = source.BudgetTotal
	entityCampaign.BudgetDaily = source.BudgetDaily
	entityCampaign.SpendTotal = source.SpendTotal
	entityCampaign.SpendToday = source.SpendToday
	entityCampaign.SpendDay = CopyTime(source.SpendDay)
	entityCampaign.Status = source.Status
	if source.PauseReason != nil {
		xstring := *source.PauseReason
		entityCampaign.PauseReason = &xstring
	}
	entityCampaign.CreatedAt = CopyTime(source.CreatedAt)
	entityCampaign.UpdatedAt = CopyTime(source.UpdatedAt)
	return entityCampaign
}
func (c *CampaignConverterImpl) ToSaveCampaignParams(source entity.Campaign) (sqlcgen.SaveCampaignParams, error) {
	var sqlcgenSaveCampaignParams sqlcgen.SaveCampaignParams
	uuidUUID, err := StringToUUID(source.CampaignID)
	if err != nil {
		return sqlcgenSaveCampaignParams, err
	}
	sqlcgenSaveCampaignParams.CampaignID = uuidUUID
	sqlcgenSaveCampaignParams.Name = source.Name
	sqlcgenSaveCampaignParams.BudgetTotal = source.BudgetTotal
	sqlcgenSaveCampaignParams.BudgetDaily = source.BudgetDaily
	sqlcgenSaveCampaignParams.UpdatedAt = CopyTime(source.UpdatedAt)
	return sqlcgenSaveCampaignParams, nil
}
