// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	uuid "github.com/google/uuid"
	sqlcgen "github.com/iPatrushevSergey/adpace/app/internal/campaign/adapter/repository/postgres/sqlcgen"
	entity "github.com/iPatrushevSergey/adpace/app/internal/campaign/domain/entity"
)

type CampaignConverterImpl struct{}

func (c *CampaignConverterImpl) ToCreateCampaignParams(source entity.Campaign) sqlcgen.CreateCampaignParams {
	var sqlcgenCreateCampaignParams sqlcgen.CreateCampaignParams
	sqlcgenCreateCampaignParams.CampaignID = c.uuidUUIDToUuidUUID(source.CampaignID)
	sqlcgenCreateCampaignParams.AdvertiserID = c.uuidUUIDToUuidUUID(source.AdvertiserID)
	sqlcgenCreateCampaignParams.Name = source.Name
	sqlcgenCreateCampaignParams.BudgetTotal = source.BudgetTotal
	sqlcgenCreateCampaignParams.BudgetDaily = source.BudgetDaily
	sqlcgenCreateCampaignParams.Status = source.Status
	sqlcgenCreateCampaignParams.CreatedAt = CopyTime(source.CreatedAt)
	sqlcgenCreateCampaignParams.UpdatedAt = CopyTime(source.UpdatedAt)
	return sqlcgenCreateCampaignParams
}
func (c *CampaignConverterImpl) ToEntityCampaign(source sqlcgen.Campaign) entity.Campaign {
	var entityCampaign entity.Campaign
	entityCampaign.CampaignID = c.uuidUUIDToUuidUUID(source.CampaignID)
	entityCampaign.AdvertiserID = c.uuidUUIDToUuidUUID(source.AdvertiserID)
	entityCampaign.Name = source.Name
	entityCampaign.BudgetTotal = source.BudgetTotal
	entityCampaign.BudgetDaily = source.BudgetDaily
	entityCampaign.SpendTotal = source.SpendTotal
	entityCampaign.SpendToday = source.SpendToday
	entityCampaign.SpendDay = CopyTime(source.SpendDay)
	entityCampaign.Status = source.Status
	if source.PauseReason != nil {
		xstring := *source.PauseReason
		entityCampaign.PauseReason = &xstring
	}
	entityCampaign.CreatedAt = CopyTime(source.CreatedAt)
	entityCampaign.UpdatedAt = CopyTime(source.UpdatedAt)
	return entityCampaign
}
func (c *CampaignConverterImpl) ToSaveCampaignParams(source entity.Campaign) sqlcgen.SaveCampaignParams {
	var sqlcgenSaveCampaignParams sqlcgen.SaveCampaignParams
	sqlcgenSaveCampaignParams.CampaignID = c.uuidUUIDToUuidUUID(source.CampaignID)
	sqlcgenSaveCampaignParams.Name = source.Name
	sqlcgenSaveCampaignParams.BudgetTotal = source.BudgetTotal
	sqlcgenSaveCampaignParams.BudgetDaily = source.BudgetDaily
	sqlcgenSaveCampaignParams.UpdatedAt = CopyTime(source.UpdatedAt)
	return sqlcgenSaveCampaignParams
}
func (c *CampaignConverterImpl) uuidUUIDToUuidUUID(source uuid.UUID) uuid.UUID {
	var uuidUUID uuid.UUID
	for i := 0; i < len(source); i++ {
		uuidUUID[i] = source[i]
	}
	return uuidUUID
}
