// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto(in *jlexer.Lexer, out *PutAdvertiserResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "country":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Country = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto(out *jwriter.Writer, in PutAdvertiserResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"country\":"
		out.RawString(prefix)
		out.String(string(in.Country))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PutAdvertiserResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PutAdvertiserResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PutAdvertiserResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PutAdvertiserResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto(l, v)
}
func easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto1(in *jlexer.Lexer, out *PutAdvertiserRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "country":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Country = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto1(out *jwriter.Writer, in PutAdvertiserRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"country\":"
		out.RawString(prefix)
		out.String(string(in.Country))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PutAdvertiserRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PutAdvertiserRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PutAdvertiserRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PutAdvertiserRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto1(l, v)
}
func easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto2(in *jlexer.Lexer, out *PatchAdvertiserResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "country":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Country = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto2(out *jwriter.Writer, in PatchAdvertiserResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"country\":"
		out.RawString(prefix)
		out.String(string(in.Country))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PatchAdvertiserResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PatchAdvertiserResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PatchAdvertiserResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PatchAdvertiserResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto2(l, v)
}
func easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto3(in *jlexer.Lexer, out *PatchAdvertiserRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
				out.Name = nil
			} else {
				if out.Name == nil {
					out.Name = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Name = string(in.String())
				}
			}
		case "country":
			if in.IsNull() {
				in.Skip()
				out.Country = nil
			} else {
				if out.Country == nil {
					out.Country = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Country = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto3(out *jwriter.Writer, in PatchAdvertiserRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Name != nil {
		const prefix string = ",\"name\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.Name))
	}
	if in.Country != nil {
		const prefix string = ",\"country\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Country))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PatchAdvertiserRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PatchAdvertiserRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PatchAdvertiserRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PatchAdvertiserRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto3(l, v)
}
func easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto4(in *jlexer.Lexer, out *GetAdvertiserResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "country":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Country = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto4(out *jwriter.Writer, in GetAdvertiserResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"country\":"
		out.RawString(prefix)
		out.String(string(in.Country))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetAdvertiserResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetAdvertiserResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetAdvertiserResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetAdvertiserResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto4(l, v)
}
func easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto5(in *jlexer.Lexer, out *ErrorResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "error":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Error = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto5(out *jwriter.Writer, in ErrorResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix[1:])
		out.String(string(in.Error))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ErrorResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ErrorResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ErrorResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ErrorResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto5(l, v)
}
func easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto6(in *jlexer.Lexer, out *CreateAdvertiserResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "country":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Country = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto6(out *jwriter.Writer, in CreateAdvertiserResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"country\":"
		out.RawString(prefix)
		out.String(string(in.Country))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateAdvertiserResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateAdvertiserResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateAdvertiserResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateAdvertiserResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto6(l, v)
}
func easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto7(in *jlexer.Lexer, out *CreateAdvertiserRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "country":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Country = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto7(out *jwriter.Writer, in CreateAdvertiserRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"country\":"
		out.RawString(prefix)
		out.String(string(in.Country))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateAdvertiserRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateAdvertiserRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateAdvertiserRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateAdvertiserRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto7(l, v)
}
