// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto(in *jlexer.Lexer, out *ResumeCampaignResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto(out *jwriter.Writer, in ResumeCampaignResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResumeCampaignResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResumeCampaignResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResumeCampaignResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResumeCampaignResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto(l, v)
}
func easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto1(in *jlexer.Lexer, out *PutCampaignResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "advertiser_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AdvertiserID = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "budget_total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BudgetTotal = int64(in.Int64())
			}
		case "budget_daily":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BudgetDaily = int64(in.Int64())
			}
		case "spend_total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SpendTotal = int64(in.Int64())
			}
		case "spend_today":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SpendToday = int64(in.Int64())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "pause_reason":
			if in.IsNull() {
				in.Skip()
				out.PauseReason = nil
			} else {
				if out.PauseReason == nil {
					out.PauseReason = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.PauseReason = string(in.String())
				}
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto1(out *jwriter.Writer, in PutCampaignResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"advertiser_id\":"
		out.RawString(prefix)
		out.String(string(in.AdvertiserID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"budget_total\":"
		out.RawString(prefix)
		out.Int64(int64(in.BudgetTotal))
	}
	{
		const prefix string = ",\"budget_daily\":"
		out.RawString(prefix)
		out.Int64(int64(in.BudgetDaily))
	}
	{
		const prefix string = ",\"spend_total\":"
		out.RawString(prefix)
		out.Int64(int64(in.SpendTotal))
	}
	{
		const prefix string = ",\"spend_today\":"
		out.RawString(prefix)
		out.Int64(int64(in.SpendToday))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	if in.PauseReason != nil {
		const prefix string = ",\"pause_reason\":"
		out.RawString(prefix)
		out.String(string(*in.PauseReason))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PutCampaignResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PutCampaignResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PutCampaignResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PutCampaignResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto1(l, v)
}
func easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto2(in *jlexer.Lexer, out *PutCampaignRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "budget_total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BudgetTotal = int64(in.Int64())
			}
		case "budget_daily":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BudgetDaily = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto2(out *jwriter.Writer, in PutCampaignRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"budget_total\":"
		out.RawString(prefix)
		out.Int64(int64(in.BudgetTotal))
	}
	{
		const prefix string = ",\"budget_daily\":"
		out.RawString(prefix)
		out.Int64(int64(in.BudgetDaily))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PutCampaignRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PutCampaignRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PutCampaignRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PutCampaignRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto2(l, v)
}
func easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto3(in *jlexer.Lexer, out *PauseCampaignResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "pause_reason":
			if in.IsNull() {
				in.Skip()
				out.PauseReason = nil
			} else {
				if out.PauseReason == nil {
					out.PauseReason = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.PauseReason = string(in.String())
				}
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto3(out *jwriter.Writer, in PauseCampaignResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	if in.PauseReason != nil {
		const prefix string = ",\"pause_reason\":"
		out.RawString(prefix)
		out.String(string(*in.PauseReason))
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PauseCampaignResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PauseCampaignResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PauseCampaignResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PauseCampaignResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto3(l, v)
}
func easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto4(in *jlexer.Lexer, out *PauseCampaignRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Reason = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto4(out *jwriter.Writer, in PauseCampaignRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"reason\":"
		out.RawString(prefix[1:])
		out.String(string(in.Reason))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PauseCampaignRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PauseCampaignRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PauseCampaignRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PauseCampaignRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto4(l, v)
}
func easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto5(in *jlexer.Lexer, out *PatchCampaignResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "advertiser_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AdvertiserID = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "budget_total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BudgetTotal = int64(in.Int64())
			}
		case "budget_daily":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BudgetDaily = int64(in.Int64())
			}
		case "spend_total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SpendTotal = int64(in.Int64())
			}
		case "spend_today":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SpendToday = int64(in.Int64())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "pause_reason":
			if in.IsNull() {
				in.Skip()
				out.PauseReason = nil
			} else {
				if out.PauseReason == nil {
					out.PauseReason = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.PauseReason = string(in.String())
				}
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto5(out *jwriter.Writer, in PatchCampaignResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"advertiser_id\":"
		out.RawString(prefix)
		out.String(string(in.AdvertiserID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"budget_total\":"
		out.RawString(prefix)
		out.Int64(int64(in.BudgetTotal))
	}
	{
		const prefix string = ",\"budget_daily\":"
		out.RawString(prefix)
		out.Int64(int64(in.BudgetDaily))
	}
	{
		const prefix string = ",\"spend_total\":"
		out.RawString(prefix)
		out.Int64(int64(in.SpendTotal))
	}
	{
		const prefix string = ",\"spend_today\":"
		out.RawString(prefix)
		out.Int64(int64(in.SpendToday))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	if in.PauseReason != nil {
		const prefix string = ",\"pause_reason\":"
		out.RawString(prefix)
		out.String(string(*in.PauseReason))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PatchCampaignResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PatchCampaignResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PatchCampaignResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PatchCampaignResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto5(l, v)
}
func easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto6(in *jlexer.Lexer, out *PatchCampaignRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
				out.Name = nil
			} else {
				if out.Name == nil {
					out.Name = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Name = string(in.String())
				}
			}
		case "budget_total":
			if in.IsNull() {
				in.Skip()
				out.BudgetTotal = nil
			} else {
				if out.BudgetTotal == nil {
					out.BudgetTotal = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.BudgetTotal = int64(in.Int64())
				}
			}
		case "budget_daily":
			if in.IsNull() {
				in.Skip()
				out.BudgetDaily = nil
			} else {
				if out.BudgetDaily == nil {
					out.BudgetDaily = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.BudgetDaily = int64(in.Int64())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto6(out *jwriter.Writer, in PatchCampaignRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Name != nil {
		const prefix string = ",\"name\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.Name))
	}
	if in.BudgetTotal != nil {
		const prefix string = ",\"budget_total\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(*in.BudgetTotal))
	}
	if in.BudgetDaily != nil {
		const prefix string = ",\"budget_daily\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(*in.BudgetDaily))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PatchCampaignRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PatchCampaignRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PatchCampaignRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PatchCampaignRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto6(l, v)
}
func easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto7(in *jlexer.Lexer, out *GetCampaignResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "advertiser_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AdvertiserID = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "budget_total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BudgetTotal = int64(in.Int64())
			}
		case "budget_daily":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BudgetDaily = int64(in.Int64())
			}
		case "spend_total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SpendTotal = int64(in.Int64())
			}
		case "spend_today":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SpendToday = int64(in.Int64())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "pause_reason":
			if in.IsNull() {
				in.Skip()
				out.PauseReason = nil
			} else {
				if out.PauseReason == nil {
					out.PauseReason = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.PauseReason = string(in.String())
				}
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto7(out *jwriter.Writer, in GetCampaignResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"advertiser_id\":"
		out.RawString(prefix)
		out.String(string(in.AdvertiserID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"budget_total\":"
		out.RawString(prefix)
		out.Int64(int64(in.BudgetTotal))
	}
	{
		const prefix string = ",\"budget_daily\":"
		out.RawString(prefix)
		out.Int64(int64(in.BudgetDaily))
	}
	{
		const prefix string = ",\"spend_total\":"
		out.RawString(prefix)
		out.Int64(int64(in.SpendTotal))
	}
	{
		const prefix string = ",\"spend_today\":"
		out.RawString(prefix)
		out.Int64(int64(in.SpendToday))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	if in.PauseReason != nil {
		const prefix string = ",\"pause_reason\":"
		out.RawString(prefix)
		out.String(string(*in.PauseReason))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetCampaignResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetCampaignResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetCampaignResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetCampaignResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto7(l, v)
}
func easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto8(in *jlexer.Lexer, out *CreateCampaignResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "advertiser_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AdvertiserID = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "budget_total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BudgetTotal = int64(in.Int64())
			}
		case "budget_daily":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BudgetDaily = int64(in.Int64())
			}
		case "spend_total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SpendTotal = int64(in.Int64())
			}
		case "spend_today":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SpendToday = int64(in.Int64())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "pause_reason":
			if in.IsNull() {
				in.Skip()
				out.PauseReason = nil
			} else {
				if out.PauseReason == nil {
					out.PauseReason = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.PauseReason = string(in.String())
				}
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto8(out *jwriter.Writer, in CreateCampaignResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"advertiser_id\":"
		out.RawString(prefix)
		out.String(string(in.AdvertiserID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"budget_total\":"
		out.RawString(prefix)
		out.Int64(int64(in.BudgetTotal))
	}
	{
		const prefix string = ",\"budget_daily\":"
		out.RawString(prefix)
		out.Int64(int64(in.BudgetDaily))
	}
	{
		const prefix string = ",\"spend_total\":"
		out.RawString(prefix)
		out.Int64(int64(in.SpendTotal))
	}
	{
		const prefix string = ",\"spend_today\":"
		out.RawString(prefix)
		out.Int64(int64(in.SpendToday))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	if in.PauseReason != nil {
		const prefix string = ",\"pause_reason\":"
		out.RawString(prefix)
		out.String(string(*in.PauseReason))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateCampaignResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateCampaignResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateCampaignResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateCampaignResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto8(l, v)
}
func easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto9(in *jlexer.Lexer, out *CreateCampaignRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "advertiser_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AdvertiserID = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "budget_total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BudgetTotal = int64(in.Int64())
			}
		case "budget_daily":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BudgetDaily = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto9(out *jwriter.Writer, in CreateCampaignRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"advertiser_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.AdvertiserID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"budget_total\":"
		out.RawString(prefix)
		out.Int64(int64(in.BudgetTotal))
	}
	{
		const prefix string = ",\"budget_daily\":"
		out.RawString(prefix)
		out.Int64(int64(in.BudgetDaily))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateCampaignRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateCampaignRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD1a9b772EncodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateCampaignRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateCampaignRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD1a9b772DecodeGithubComIPatrushevSergeyAdpaceAppInternalCampaignPresentationHttpDto9(l, v)
}
